[constraints]
gradients.inner.min = 0.5
gradients.inner.max = 1
gradients.outer.min = 0.5
gradients.outer.max = 1
radii.inner.max = 5
radii.outer.max = 5

# Configuarates style settings for gmsh (table names must not be modified)
# Options can be all sorts of options applicable for gmsh.view
[visualization]
radii = "mark_red"
gradients = "mark_red"
angles = "angles"

[styles.default]
ColormapNumber = 4
SaturateValues = 0
ShowScale = 0

[styles.mark_red]
ColormapAlpha = 1
ColormapBias = 0
ColormapCurvature = 0
ColormapNumber = 16
ColormapRotation = 0
SaturateValues = 0
ShowScale = 0
RangeType = 2

[styles.angles]
ColormapNumber = 4
ShowScale = 1
