[package]
name = "rust-methods"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_methods"
crate-type = ["cdylib"]

[dependencies]
kdtree = "0.7.0"
numpy = "0.19.0"
pyo3 = "0.19.0"
